source:      .
destination: ./_site
plugins:     ./_plugins
posts: 	     ./_posts
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
markdown: kramdown
name: Zhan Zhuang Chi Kung
description: A Arte do Cultivo da Quietude
url: http://devagar.org
safe: true
lsi: false

