source:      .
destination: ./_site
plugins:     ./_plugins
posts: 	     ./_posts
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
markdown: kramdown
name: Zhan Zhuang Chi Kung
description: A Arte do Cultivo da Quietude
url: http://lourencoazevedo.com
safe: true
lsi: false
highlighter: 'pygments'

# Open Graph
og_image: pimagens/mawangdui.jpg # Default image for Open Graph tag
og_image_type: image/jpg
og_image_width: 800

